# Generated by Django 4.1.7 on 2023-03-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prod_price',
        ),
    ]
