# Generated by Django 4.1.7 on 2023-03-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_cart_prod_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prod_qty',
        ),
    ]
