# Generated by Django 4.1.7 on 2023-03-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_cart_prod_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
