# Generated by Django 4.1.7 on 2023-03-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_tag_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tagname',
        ),
    ]
