# Generated by Django 4.1.7 on 2023-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published_on',
        ),
    ]
